name: ma_probabilistic_forecast

channels:
  - defaults

dependencies:
  - python=3.10
  - netcdf4
  - xarray
  - dask
  - bottleneck
  - geopandas
  - atlite
  - jupyterlab
  - scikit-learn
  - ngboost
  - seaborn
  - ephem
  - pypsa